### ISSUE TITLE
[Question] Can it block tracking URLs

### ISSUE THREAD

**Issue by Suleman-Elahi** [trockerapp/trocker#1]
In my email I have a URL like this:

https://signl.live/tracker/click?redirect=https%3A%2F%2Fwww.ilovefreesoftware.com%2F&dID=1537935418274&linkName=https://www.ilovefreesoftware.com/

Now, if I click on it then the tracker will know that I actually clicked on it. But I don't want that. Is there any way to reach the target URL without letting know the tracker ?

**Comment by trockerapp** [comment]
This tracker has been added as of [commit 43d9ed3](https://github.com/trockerapp/trocker/commit/43d9ed30a445a1472e2401bcd938b532db674c46).
