### ISSUE TITLE
Trocker blocks my ability to switch between signatures in Gmail

### ISSUE THREAD

**Issue by yoshkinawa** [trockerapp/trocker#10]
Hey Trocker,
I love your app very much.
Since the last update, Trocker blocks my ability to switch signatures in G

mail, when I switch my sending email.

Please fix it and let me know...

**Comment by trockerapp** [comment]
Thank you very much for reporting this and for the video. Thanks to your video, we have been able to reproduce the issue and will be working on fixing it for the next update.
