### ISSUE TITLE
Not working at all in Gmail

### ISSUE THREAD

**Issue by billbraskey777** [trockerapp/trocker#13]
I've installed Trocker on Chrome (Version 89.0.4389.82) and cannot find any trace of it in gmail. 

I tried using it in incognito mode, verifying that it was the single, only extension enabled, and it still was nowhere to be found.

**Comment by trockerapp** [comment]
Trocker doesn't change the Gmail interface, unless there is a tracker detected. To confirm that Trocker is running, can you please check the console logs in the [Chrome Dev Tools](https://developers.google.com/web/tools/chrome-devtools/open) in a tab that has Gmail opened? If trocker is running, you should be able to find a message like the following somewhere in the early logs:
```
Trocker ready!
[Trocker] Env="gmail"
```

**Comment by billbraskey777** [comment]
Confirmed in the console that Trocker is running. I dug around some more and did find some e-mails where it was working, so I think I'm all good. My first look was just on a few e-mails that I thought certainly would have tracking embedded but none was found.
