### ISSUE TITLE
Using FireFox and Outlook webmail: Trocker blocks the Office 365 icons in the leftmost columns in Outlook(Hotmail)

### ISSUE THREAD

**Issue by Mac404** [trockerapp/trocker#19]
Hi

I normally log into my Outlook/Hotmail account using the latest Firefox (94.0.2). I turned on/off all my other plugins/add-ons/extensions and found out Trocker is blocking the Office 365 icons in the leftmost columns in Outlook or Hotmail

Thanks

![Trocker Disabled](https://user-images.githubusercontent.com/70410606/144315449-3300ad1e-9f2b-4b2a-8f45-705bc0e62f9e.png)
![Trocker Enabled](https://user-images.githubusercontent.com/70410606/144315454-6111a12c-1582-4199-ac72-fa6163f9f639.png)

**Comment by trockerapp** [comment]
Thank you for reporting the issue. This issue has been fixed in version 2.6,19, which is rolling out now on Firefox.

**Comment by Mac404** [comment]
I just tested it and it works now. Thank you for all your help :)
