### ISSUE TITLE
Images No Longer Displayed in Gmail using Chrome

### ISSUE THREAD

**Issue by jsetton** [trockerapp/trocker#24]
It seems that images are no longer being displayed in Gmail using Chrome recently. I first thought it could have been related to the Chrome UI Refresh 2023 but disabling that feature didn't seem to resolve the matter. This started with Chrome 118 but it may not be related to a specific browser.

**Comment by trockerapp** [comment]
Thanks for reporting. We were able to replicate and fix the issue. The the next update (v2.6.24) fixing the issue is currently pending webstore approval.

**Comment by ThePieMonster** [comment]
> Thanks for reporting. We were able to replicate and fix the issue. The the next update (v2.6.24) fixing the issue is currently pending webstore approval.

What ended up being the issue out of curiosity? Something Google updated it would seem.

**Comment by beastielper** [comment]
I have exactly the same issue on Firefox 115.4.0esr 64-bit. Tracker version 2.6.23.

**Comment by Vad1mo** [comment]
I can confirm, this too.

**Comment by trockerapp** [comment]
Thanks for reporting everyone. The same v2.6.24 that is now rolling out on Firefox should fix the issue.

**Comment by trockerapp** [comment]
> > Thanks for reporting. We were able to replicate and fix the issue. The the next update (v2.6.24) fixing the issue is currently pending webstore approval.
> 
> What ended up being the issue out of curiosity? Something Google updated it would seem.

An update in the Gmail design had broken the CSS selector that Trocker used to find opened emails in the Gmail interface. When enabled, Trocker blocks all Gmail images from loading until they are checked and appear safe. So not being able to find the emails in the Gmail interface meant that images were never checked, so they were never allowed to load. Fortunately, Gmail changes usually don't break CSS selectors, so bugs like this are rarely introduced.

**Comment by jsetton** [comment]
Thanks for the quick turnaround. I can confirm that v2.6.24 resolved the issue on Chrome.
