### ISSUE TITLE
trocker blocking *all*(?) images in Gmail email

### ISSUE THREAD

**Issue by edjusted** [trockerapp/trocker#25]
This started happening maybe a few days or so ago. All email viewed in Gmail with inline images are broken, with all images not loading. Disabling Trocker in Chrome (on a Mac, at least) re-enables images.

**Comment by trockerapp** [comment]
Thanks for reporting. This has been fixed as of v2.6.24 (see Issue #26), which is rolling out on Firefox but is still pending Webstore approval before it rolls out on Chrome.

**Comment by edjusted** [comment]
Thanks for the quick fix!
