### ISSUE TITLE
feature request: "Redirecting in" controllable number of seconds

### ISSUE THREAD

**Issue by illucent** [trockerapp/trocker#7]
Hi Awesome and very useful extension.
Would you like to consider my proposal to add
```Redirecting in <number_of_seconds>s```
"number of seconds" to options?
Thanks!

**Comment by trockerapp** [comment]
This feature has been added in [77799a0](https://github.com/trockerapp/trocker/commit/77799a03eab17f73a7e60d6bdef9e88c65ddecf9).

**Comment by illucent** [comment]
Thanks a lot!
